spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/readmedia"
    username: "postgres"
    password: "root"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "update"
